### ISSUE TITLE
DromedaryRepo param is redundant and not used

### ISSUE THREAD

**Issue by dmbettinger** [stelligent/dromedary#60]
There’s a DromedaryRepo param in the stack with a default value of "https://github.com/stelligent/dromedary.git”.  But I think it gets ignored.  I think the actual github URL gets constructed from the github user and repo params.

**Comment by PaulDuvall** [comment]
It doesn't get ignored as it's used [here](https://github.com/stelligent/dromedary/blob/master/pipeline/cfn/dromedary-master.json#LL1037-LL1039), but it probably *should* be unnecessary as I should be using an `Fn::Join` to concatenate the URL from the `GitHubUser` and `Repo` parameters.

**Comment by dmbettinger** [comment]
Your change will bring it in line with codepipeline-cfn.json which uses GitHubUser and Repo params to configure the Source stage of the pipeline.
